### ISSUE TITLE
Not working - Ubuntu 20.10 - Gnome 3.37.90

### ISSUE THREAD

**Issue by jeremie2** [emasab/shelltile#106]
Hi,
I'm testing ShellTile on the forthcoming Ubuntu 20.10, at this stage with Gnome 3.37.90.
I presume something has been change in the new version of Gnome, so that the extension is no more compatible.

Installing ShellTile from **extensions.gnome.org** the page displays the **ERROR** red button. It doesn't work also downloading the extension directly from GitHub.
I tried also other similar extensions e none of them work... except Keypad Tiling, which is a simplified tiling window extension that works just using keyboard shortcuts.

Cheers!

**Comment by jjosborne** [comment]
Been having same problem.

JS ERROR: Extension ShellTile@emasab.it: ImportError: No JS module 'tweener' found in search path

**Comment by pstolarz** [comment]
Same on 3.38. I solved the problem as described here: #110.

**Comment by emasab** [comment]
solved with the changes described here

https://github.com/emasab/shelltile/issues/110
