### ISSUE TITLE
Occasionally, grid preview stays active after window snapping.

### ISSUE THREAD

**Issue by gedgon** [emasab/shelltile#11]
The title says it all.
Screencast: https://www.dropbox.com/s/9k27yr6kydoa465/Shelltile-tile-preview.mp4?dl=0

**Comment by emasab** [comment]
hi, do you have the latest version from github ? I've tried that movement, but couldn't reproduce it

**Comment by gedgon** [comment]
Yes, it's the latest version.
Happens rather randomly, but quite often, and I'm not sure if the movement is important. I'll check GNOME 3.18. Maybe it's not triggered there.

**Comment by gedgon** [comment]
Yup, it's reproducible also in GNOME 3.18 (Fedora 23 Live).

**Comment by bitstrings** [comment]
Yeah, I'm getting this also.

Clicking on the titlebar will make it disappear.

This is annoying.

**Comment by emasab** [comment]
Could you try this ?

[tiling.js.zip](https://github.com/emasab/shelltile/files/478638/tiling.js.zip)

**Comment by emasab** [comment]
It happed to me too, can you try this change ? It seems to resolve.

[tiling.js.zip](https://github.com/emasab/shelltile/files/478653/tiling.js.zip)

**Comment by gedgon** [comment]
Works great. Thanks!
