### ISSUE TITLE
Doesn't work on gnome 3.38

### ISSUE THREAD

**Issue by pstolarz** [emasab/shelltile#110]
Since `ui.tweener` module is removed in gnome 3.38 (see [here](https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/905) for details), the extension doesn't work on this version of shell.

Changing `Tweener` import in `tiling.js` (line 7) from
`const Tweener = imports.ui.tweener;`
to
`const Tweener = imports.tweener.tweener;`
fixed the problem.

**Comment by emasab** [comment]
Hi, thanks for your contribution! I've included the fix in the last commit. Tell me if there are other problems with the last version of GNOME.

https://github.com/emasab/shelltile/commit/1b63126a112861d964873b812f6af31b3a063fc6

**Comment by pstolarz** [comment]
Thanks for quick fix. Unfortunately there is a small issue with it. #111 contains proper version.
As far as everything works fine on 3.38. Thanks for the great extension. Good job.

**Comment by emasab** [comment]
Please try the latest version on master, it's only a bit different from your PR for backward compatibility reasons

**Comment by pstolarz** [comment]
Works fine, thanks.

**Comment by meeas** [comment]
Confirmed everything working fine with Master on Debian Sid with Gnome 3.38.  I think the only thing missing is adding 3.36 and 3.38 to metadata.json and pushing it up to Gnome Extensions website.

**Comment by emasab** [comment]
Done, thanks for the reminder
