### ISSUE TITLE
Does not work on GNOME version 42.0

### ISSUE THREAD

**Issue by MKsutov** [emasab/shelltile#135]
**Describe the bug**
The extension in incompatible with the GNOME version shipped with Ubuntu 22.04 (version 42.0).

**To Reproduce**
1. Install Ubuntu 22.04
2. Go to Gnome extensions app

**Expected behavior**
 ShellTile is incompatible with GNOME v. 42.0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04 LTS]
 - Gnome version 42.0 (as seen in "about" section in Ubuntu settings)

**Comment by crown-bdee** [comment]
See the workaround described in theychx/WorkspaceSwitcherWrapAround#10.
The same worked for me with this extension seemingly without issue so far (just add 42 to the list for Ubuntu 22.04 support, and logout & back in).

**Comment by svenuthe** [comment]
I have the same problem on Fedora 36.
When I add 42 as a supported version I get the following error:
```
Error: No property margin on GtkBox

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:55:50
  buildPrefsWidget@~/.local/share/gnome-shell/extensions/ShellTile@emasab.it/prefs.js:94:16
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```

**Comment by MKsutov** [comment]
> See the workaround described in [theychx/WorkspaceSwitcherWrapAround#10](https://github.com/theychx/WorkspaceSwitcherWrapAround/issues/10). The same worked for me with this extension seemingly without issue so far (just add 42 to the list for Ubuntu 22.04 support, and logout & back in).

Worked like a charm; thanks!

**Comment by crown-bdee** [comment]
> I have the same problem on Fedora 36. When I add 42 as a supported version I get the following error:
> 
> ```
> Error: No property margin on GtkBox
> 
> Stack trace:
>   _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:55:50
>   buildPrefsWidget@~/.local/share/gnome-shell/extensions/ShellTile@emasab.it/prefs.js:94:16
>   _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
>   ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
>   OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
>   asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
>   run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
>   main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
>   run@resource:///org/gnome/gjs/modules/script/package.js:206:19
>   start@resource:///org/gnome/gjs/modules/script/package.js:190:8
>   @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
> ```

I wonder if this is a difference between the Ubuntu flavor of Gnome and the pure Gnome (I'm using the former).

#123 seems to capture this issue
