### ISSUE TITLE
add three column layout

### ISSUE THREAD

**Issue by nzjrs** [emasab/shelltile#16]
With very hight horizontal resolution monitors (>2880) it is common to have three columns of layout. It would be great if the extension supported this.

**Comment by emasab** [comment]
Hi, to achieve this you can tile two windows vertically, resize the right one to approximately 66% of the screen and then tile the third window vertically with this one.

**Comment by nzjrs** [comment]
shame about the manual resizing step

**Comment by emasab** [comment]
I know. An improvement could be: select the split percentage according to the position of the cursor when tiling. Updating the preview accordingly
