### ISSUE TITLE
Odd results with multiple monitors

### ISSUE THREAD

**Issue by bongfrog** [emasab/shelltile#17]
Thanks for a great extension.
    I am having some issues with this extension when my laptop is connected to an external monitor.    It seems that the screen edge triggers one the second monitor result in the window jumping back to the primary.   The shaded window that shows position are drawn on the primary.

I do want to remark that I am running Gnome on Fedora 25 with Wayland and will test with X11 when I get a chance.

Thanks again

**Comment by Hjdskes** [comment]
Can confirm that this extension does not behave as it should on Wayland with two monitors.

**Comment by ehuisman** [comment]
It doesn't work with two monitors without Wayland (with X, that is), either. I did some testing and it seems that at least for me, the problem is connected to the fact that I have the external display is configured as the primary even though it has assigned number 2. If I switch my laptop display to be the primary, this extension works as expected on both screens.

**Comment by emasab** [comment]
Can you post a screenshot of the disposition ? Like this 
<img width="1152" alt="screen1" src="https://cloud.githubusercontent.com/assets/2727141/22329658/9653fc08-e3c2-11e6-9467-db9072ec8e91.png">

**Comment by ehuisman** [comment]
Screenshot as requested:

![shelltile](https://cloud.githubusercontent.com/assets/1159338/22336036/9157c3ac-e3e9-11e6-9e3e-237108d47ce4.png)

**Comment by emasab** [comment]
Thanks, I've reproduced the problem, but don't know the cause yet.

**Comment by bongfrog** [comment]
Good morning.   
      My tests with X11 had other issue with multiple monitors so I did not complete but in Wayland I wanted to point out a very interesting fact that I noticed.   When I attempt to position a window on one of the monitors the "target area" actually shows up on the opposite monitor and the window lads there as well.       Monitor 1 (laptop display) is my primary   and 2 is a 4K TV in service as a monitor.    As I said I am able to make use but draging a window to the opposite monitor is not idea.   

Once again thanks for your hard work.
![screenshot from 2017-01-26 09-04-05](https://cloud.githubusercontent.com/assets/5440672/22339328/d1f6493a-e3a6-11e6-809e-cf30354643c5.png)

**Comment by bongfrog** [comment]
FYI    This appears to be a little deeper of a Wayland type issue as I am also noticing that QUAKE's display screen setting does not seem to be respected as well.    When the setting is for primary monitor the drop down appears on either randomly.

Thanks again

**Comment by VinnyFonseca** [comment]
I have a laptop with an external monitor plugged in via mini displayport. For me, the issue is that I set the external monitor to primary and the laptop to secondary. It seems the extension is using another parameter to detect what's left or right. When I set my laptop monitor to primary, it worked with no issues.

**Comment by emasab** [comment]
Yes, it's related to the primary setting

**Comment by VinnyFonseca** [comment]
Did you know this before, or is it something I shone some light on? Any ideas for a possible fix?

**Comment by emasab** [comment]
I had verified it when I've reproduced the bug, but I have to work on the code to find the solution.

**Comment by VinnyFonseca** [comment]
Cool, thanks. Keep us posted :)

**Comment by emasab** [comment]
this should be solved by the latest changes on the master branch

**Comment by VinnyFonseca** [comment]
Thanks, will test it tomorrow and let you know.

**Comment by mhellmeier** [comment]
Thanks a lot. I tested it on Ubuntu 16.04 with GNOME Shell 3.18.5 and it works.

I think there are still problems with grouping and two monitors. Sometimes the group jumps to the other screen, sometimes I can't create a group (yes, I am using the CTRL key).

**Comment by VinnyFonseca** [comment]
Thanks @emasab, working flawlessly now. Ubuntu 16.04 and GNOME Shell 3.20.4. I haven't encountered the issues @mhellmeier found, but that's anecdotal. Any idea when will the update be available on gnome.extensions.org?

**Comment by emasab** [comment]
there is a new version on extensions.gnome.org, waiting for approval

**Comment by bongfrog** [comment]
I just was able to get my Shelltile updated to the version on gnome.org and it seems to have corrected the issues I was 
having   (wayland / multiple monitor).  Windows are moving to the correct screen ,  the control groupings actually seem 
to work now.    Thanks for all of the hard work!!!
