### ISSUE TITLE
Tiling on top starts too early

### ISSUE THREAD

**Issue by ThanosApostolou** [emasab/shelltile#19]
Dragging a window to the top starts tiling before the mouse touches the top edge. This doesn't really matter when you have panel on top, but if you have panel at bottom by using an extension like "Dash to Panel", then it becomes impossible to drag a window to the top (by using only mouse and not the window action key) without tiling it. I don't know if you have done this behaviour intentionally (for easier tiling) but it would be nice if tiling was happening only on the screen edge or add an option at preferences for users who want it that way. Maybe some milliseconds delay before tiling is activated would also be helpful.

Screenshot showing the problem:
![screenshot from 2017-02-16 11-38-08](https://cloud.githubusercontent.com/assets/21288843/23015822/ee2f80b6-f43c-11e6-8afb-a1f06d8e9bce.png)

**Comment by fbruetting** [comment]
I have this issue, too. Do you also have an UHD screen? Maybe it's due to the higher resolution…

**Comment by ThanosApostolou** [comment]
@fbruetting My resolution is 1920 x 1080

**Comment by lostpebble** [comment]
This is making this extension almost impossible to use for me. I have monitors which don't have any panels on them and I like keeping my windows maximised and split horizontally across the screen.

When I go to click on the app top bar to movie it around slightly, it automatically straight away thinks I want to snap it to the top of the screen / or maximise it on the screen.

I wish you could set key that needs to be held down for any shell tile functionality to be enabled. That way I can be more deliberate when I want tiled windows on certain parts of the screen, but also be able to move / resize windows naturally without this extension jumping the gun.

**Comment by ddnexus** [comment]
ShellTile ignores whether the top bar is hidden or not: it always behave like the top bar is there.

Besides, the behavior takes into account the cursor anchor point, not the window edge. Pinching the window on the very bottom of the title bar or on the very top of it, allows to move the window closer or more far to to edge of the screen.

It looks like it needs 2 fixes:

1. consider the actual screen area available to the window
2. trigger the behavior considering the window edge and not the cursor anchor point

**Comment by ddnexus** [comment]
A quick fix/hack that will make it usable, when you have the Top Bar to the bottom:

- Open: `~/.local/share/gnome-shell/extensions/ShellTile@emasab.it/util.js`
- Search `var top_zone = new Meta.Rectangle({ x: monitor_geometry.x, y: monitor_geometry.y, width: monitor_geometry.width, height: main_panel_rect.height - 28});`
- Subtract the (height of your Top Bar - 20) as follow (in my case, using Dash to Panel height of 48, I subtract  48-20=28): `var top_zone = new Meta.Rectangle({ x: monitor_geometry.x, y: monitor_geometry.y, width: monitor_geometry.width, height: main_panel_rect.height - 28});`
- Restart the gnome-shell (Alt-F2 + r)
- Enjoy

You will have to adjust or remove the change depending on the size and location of the Top Bar.

**Comment by ddnexus** [comment]
Optional step to make it symmetrical also on the bottom:

- Search: `var bottom_zone = new Meta.Rectangle({ x: monitor_geometry.x, y: monitor_geometry.y + monitor_geometry.height - main_panel_rect.height , width: monitor_geometry.width, height: main_panel_rect.height });`
- Add the same number: `var bottom_zone = new Meta.Rectangle({ x: monitor_geometry.x, y: monitor_geometry.y + monitor_geometry.height - main_panel_rect.height + 28 , width: monitor_geometry.width, height: main_panel_rect.height });`

**Comment by ddnexus** [comment]
I created a pull-request that solves the issue.
