### ISSUE TITLE
Override super-left and super-right

### ISSUE THREAD

**Issue by Vaesper** [emasab/shelltile#23]
The default gnome shell has this window-snapping thing bound to these keys. I'd prefer them to behave in the same way as super-dragging a window to either side works with shelltile; ie. still be resizable.

**Comment by pofl** [comment]
Oh yes please!

What I hate about Super+Arrow shortcuts is that the windows won't be resizable.

**Comment by emasab** [comment]
see https://github.com/emasab/shelltile/issues/25
