### ISSUE TITLE
What about shortcuts?

### ISSUE THREAD

**Issue by g4rrucho** [emasab/shelltile#25]
Is it possible to assign keys to specific actions like moving windows to right or left?

Better yet, a way that the extensions handles windows automatically in the desktop, with the bindkeys to move windows, like i3wm

**Comment by ElectricPrism** [comment]
I would like to follow up on this and request the ability to bind the following shortcuts:

Left
Right
Top
Bottom
Top Left
Top Right
Bottom Left
Bottom Right

These shortcuts would add a lot of value to an already amazing extension, thank you.

**Comment by hackel** [comment]
Agreed, one of the main benefits of a tiling window manager is the ability to get away from the mouse.  Some VIM-style keybindings would be great!

**Comment by fbob** [comment]
+1 A must have feature
Anyway awesome work :)

**Comment by emasab** [comment]
They are in the latest version (on github, soon on extensions.gnome.org) Super+Arrows or Super+Double up for half horizontal upper tiling
