### ISSUE TITLE
How to disable Group windows?

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [emasab/shelltile#34]
I like the feature, but I want it to disable it, mainly because I drag the windows a lot using `alt+click+drag` (in my case `super+click+drag`)  and it breaks my workflow...

**Comment by emasab** [comment]
in my case means that you've changed alt+click+drag to super+click+drag ? The change from Ctrl to Super is important for the meaning of the key that is linked to the WM and uniformity with new shortcuts that should be super+arrows, if possible.

**Comment by RicardoEPRodrigues** [comment]
Yes, I changed the `alt` to `Super`. The last update made so that when I drag without clicking on the menu-bar it tries to group the window with others, I don't want that grouping (at least not with those keys).

**Comment by RicardoEPRodrigues** [comment]
**UPDATE** I found the bug, so to speak. The intended grouping mechanism is when holding `Ctrl` while dragging a window it starts grouping.

In GNOME Tweak tool I changed the `Window Action Key` from `Alt` to `Super`, meaning that for me to drag a window without clicking and dragging from the menu bar I use `Super+Click+Drag` instead of `Alt+Click+Drag`.

The bug rises here, because using this setup when dragging a window it always triggers the grouping, when it shouldn't.

**Comment by emasab** [comment]
in the meantime you can change 

`
var modifiers = Clutter.ModifierType.CONTROL_MASK | Clutter.ModifierType.MOD4_MASK;
`
to
`
var modifiers = Clutter.ModifierType.CONTROL_MASK;
`
in 
`
~/.local/share/gnome-shell/extensions/ShellTile@emasab.it/tiling.js
`
then restart the system or restart gnome shell with Alt+F2 -> r<Enter>

**Comment by RicardoEPRodrigues** [comment]
It worked perfectly. Thank you!

**Comment by Vaesper** [comment]
Ahh, thanks for this, I had the same issue. Any chance to get the super-key-binding configurable?

**Comment by lagerspetz** [comment]
I just made a pull request for this: https://github.com/emasab/shelltile/pull/42

**Comment by lagerspetz** [comment]
I think this can be closed, @RicardoEPRodrigues  ?

**Comment by RicardoEPRodrigues** [comment]
Yes. The current release already fixed the issues right?
