### ISSUE TITLE
Can't lock screen

### ISSUE THREAD

**Issue by Naydan** [emasab/shelltile#35]
Can't lock screen using _SUPER+L_ after enabling ShellTile. _SUPER+L_ now tiles windows like i3 commands, which may be fine for some users, but I need to be able to lock my screen. I've tried other keyboard shortcuts to lock the screen and for some reason they don't work with ShellTile enabled.
Would it be possible to add an option to disable those shortcuts so I can tile just by using the mouse?

**Comment by emasab** [comment]
Hi Naydan, please install the latest version on extensions.gnome.org (accepted this morning). I've removed those shortcuts

**Comment by Naydan** [comment]
Thanks emasab, all works fine now.
