### ISSUE TITLE
Allow both maximized and unaximized at the same time

### ISSUE THREAD

**Issue by lumnn** [emasab/shelltile#36]
Currently extension allows to have groups either maximized or not. It would be nice to have both groups at once.

I'm not sure how I'd like this to work, because right now maximising a window ungroups it. Perhaps it could be changed to Ctrl key (so you group, and ungroup window using the same key), and then maximizing and unmiximising window, would maximise or unmaximise group

**Comment by erpl** [comment]
Seems to be related to #26 .

**Comment by emasab** [comment]
There is a feature that was gone a bit undocumented, hold Ctrl while maximizing and when you unmaximize the window will stay grouped.

**Comment by erpl** [comment]
Wörd! That's exactly what I was looking for. Thank for letting me! (bow) If you and the OP agree, this ticket and lase #26 can be closed.
