### ISSUE TITLE
For Emacs dragging to the size doesn't maximize to half of the screen (leaves space at bottom)

### ISSUE THREAD

**Issue by alothings** [emasab/shelltile#38]
As the title says, I am only encountering this issue with Emacs, and it is the application that I use the most, so it gets a bit frustrating after a while.

Whenever I drag emacs to the sides (both right and left), it is supposed to maximize to cover such half of the screen. However, with Emacs it leaves a small 
![shelltile_example](https://cloud.githubusercontent.com/assets/4199458/25776866/c34e7d4e-3298-11e7-9f44-6308113db6bf.png)
![shelltile_example2](https://cloud.githubusercontent.com/assets/4199458/25776865/c34c90f6-3298-11e7-96e0-39694cd88e18.png)

space at the bottom. And it does not let me resize it. Also whenever I drag the window to the corners like top right or bottom right, for instance, it leaves a space at the bottom and at the right.

**Comment by alothings** [comment]
No idea what happened, but after updates it was fixed.

**Comment by alothings** [comment]
Still happening.

**Comment by emasab** [comment]
this happens because the terminal forces the width and height to be a multiple of the cursor width and height. If you try to resize it manually you should see that it resizes with steps of several pixels.
