### ISSUE TITLE
Don't arbitrarily change keybindings

### ISSUE THREAD

**Issue by btittelbach** [emasab/shelltile#39]
Hi,

- When activating shell-tile extension, my custom keybindings for Super+ArrowKey are changed without asking.

- There are no configuration options (not even in dconf) to change the keybindings shelltile uses.

- While shell-tile is active, keybindings for "maximize window" and "restore window" can't be changed so I can't manually restore my keybindings AND use shell-tile. (maximize/restore window keybindings are not needed anyway, since Super+Return already switches between these two states)

- Even worse, when I disable shell-tile in frustration, my keybindings are NOT restored.

That is really bad behaviour and sours the experience of what would otherwise be a very helpful tool.

**Comment by emasab** [comment]
Do you have the latest version ? I've removed the keybindings.

**Comment by detly** [comment]
I had the same problem (with meta+L for locking the screen) and updating fixed it 👍

**Comment by btittelbach** [comment]
I have the newest version.
I can see where the keybindings were commented out in the code.

**Issue remains though!**

The moment I activate shelltile, my keybindings for Maximize/Restore Window 
are reset to Super-Up/Down and remain unchangeable while the extension is active.
I can confirm that this is the behaviour of the newest version, that I restarted several times in between and that no legacy shelltile code is lying around somewhere.

**Comment by emasab** [comment]
Ok, now I understand what's happening. When I've removed the keybindings I've added a piece of code that upon activation resets those values to the defaults, because the previous version removed the default keybindings in order to overwrite them. I have to keep that code for some time, if you want to overwrite those keybindings remove these lines in


`~/.local/share/gnome-shell/extensions/ShellTile@emasab.it/extension.js`


```
self.keybindingSettings.reset("maximize");
self.keybindingSettings.reset("unmaximize");
self.keybindingSettingsMutter.reset("toggle-tiled-left");
self.keybindingSettingsMutter.reset("toggle-tiled-right");
```

**Comment by emasab** [comment]
or you can set those values to the default, so that reset will always revert to those values,
following this tutorial

https://askubuntu.com/questions/65900/how-can-i-change-default-settings-for-new-users

**Comment by btittelbach** [comment]
I tried changing the default values which worked fine and does not interfere with semiautomatic shelltime upgrades.

Glad I can finally use shelltile without hassle :-)
Still looking forward to a more permament solution though.
