### ISSUE TITLE
The 'Super' key behaves like the 'Control' (it's a problem sometimes)

### ISSUE THREAD

**Issue by DLakomy** [emasab/shelltile#40]
When I move a window with the 'Super' key pressed, the extension's behaviour is the same as if I kept the 'Control' pressed - tiling is enabled. It's a problem for me, since I use 'Super'+LeftMouseButton to move windows. I use Gnome 3.22.2. I think one should be able to choose which key they want to use.

**Comment by jedypod** [comment]
This is an issue for me as well... Reverting to a previous version until this is fixed.

**Comment by ntkoopman** [comment]
I'm pretty sure I saw this in another issue, but you can work around this by modifying `~/.local/share/gnome-shell/extensions/ShellTile@emasab.it/tiling.js`:
On line 595 change 
```js
var modifiers = Clutter.ModifierType.CONTROL_MASK | Clutter.ModifierType.MOD4_MASK;
```
 to
```js
var modifiers = Clutter.ModifierType.CONTROL_MASK;
```

But a configuration option would be nice.

**Comment by RicardoEPRodrigues** [comment]
I made a still open issue. #34

**Comment by lagerspetz** [comment]
This is affecting me too. I use Inkscape to draw vector graphics, and it makes heavy use of alt and ctrl, so my window move modifier is Super, not Alt. Moving windows with Super - Left drag makes them tile, even though the documentation for this widget specifies Ctrl. Ctrl is great in my opinion. If you want to enable other keys too, please let people change that.

**Comment by lagerspetz** [comment]
I just made a pull request for this: https://github.com/emasab/shelltile/pull/42

**Comment by emasab** [comment]
Hi, I've heard your complains and remove the usage of the super key. It was introduced along with the super+keys shortcuts, but given that shotcuts have been removed, I remove it too. It will come back if configurable and the shortcuts would have to be configurable too. I've pushed the commit and the new version is on gnome shell.
