### ISSUE TITLE
Moving windows between workspaces takes the whole group

### ISSUE THREAD

**Issue by hovissimo** [emasab/shelltile#45]
To reproduce:

Set up Gnome with more than one workspace.
Set up two windows in a tiling group (with ctrl-drag, whatever)
Alt tab such that one of those windows is focused.
Hit Ctrl-Shift-Alt-Arrow to move that window to the other workspace
Notice that both windows came to the new workspace
Hit Ctrl-Alt-Arrow to go back to the first workspace
Notice that neither window  is on the first workspace anymore.

**Comment by Gi60s** [comment]
I actually prefer this behavior, but it would be nice to add an option for it in the preferences.

**Comment by johannesgunnar** [comment]
Came here to say that this is the behaviour that I expect and prefer from it. But like Gi60s said, would probably be good to have an option for it.

**Comment by hovissimo** [comment]
A few months in, and I've decided I like this behavior too. I'm going to close the issue.
