### ISSUE TITLE
Only maximized windows remember their size

### ISSUE THREAD

**Issue by marekjedrzejewski** [emasab/shelltile#53]
When window is groupped, snapped to corner, snapped to edge, when ungrouped/unsnapped, the size stays the same as in group/snapped one.
When maximizing by snapping to top edge, windows dragged away from it, resizes to its previous size.
If I use win+left, win+right, window remembers its previous size, but I presume that's because it's using standard gnome snapping for it.

Installed from gnome extensions. Does it have up-to-date version?

**Comment by emasab** [comment]
should be solved now
