### ISSUE TITLE
unwanted horizontal gaps below tiled windows on gnome 3.28 wayland

### ISSUE THREAD

**Issue by pitlochry** [emasab/shelltile#64]
On gnome 3.28.2 on wayland there are unwanted horizontal gaps below tiled windows, although in ShellTile settings "Size of the gaps between the windows" is set to 0, see
![screenshot with 4 tiled windows](https://user-images.githubusercontent.com/41258895/43357136-539a4262-927d-11e8-8a2b-636cd88b1fbc.png)

FYI: The gTile extension shows the same behaviour on gnome 3.28 wayland.

**Comment by emasab** [comment]
Please try with a different type of window, gnome-terminal and some others have like a snap to grid feature that causes the height to be a multiple of the line height and we cannot do anything about it.

**Comment by pitlochry** [comment]
You are totally right, this is a "feature" of gnome-terminal. Thank you. Other windows tile as expected. Allas, this "feature" of gnome-terminal cannot be disabled.
