### ISSUE TITLE
Shortcuts feature

### ISSUE THREAD

**Issue by hosseio** [emasab/shelltile#69]
It would be awesome to be able to configure keyboard shortcuts for single window tiling

**Comment by Tumerskiy** [comment]
totally agreed

**Comment by emasab** [comment]
It's included in version 61, with configurable shorcuts and defaults to:

<Ctrl><Super>Left : Tile to the left border
<Ctrl><Super>Right : Tile to the right border
<Ctrl><Super>Up : Tile to the top border
<Ctrl><Super>Down : Tile to the bottom border
