### ISSUE TITLE
Can't snap window to top

### ISSUE THREAD

**Issue by detly** [emasab/shelltile#7]
If I ctrl+drag a window to the bottom of an empty screen, a highlight appears that covers the lower 50% of that screen, and the window snaps to that area. If I ctrl+drag it to the top, the highlight only covers the whole screen, and the window can only be maximised. There seems to be no way to snap to the top half of an empty screen.

Gnome shell: 3.18.5 under Ubuntu 16.04

**Comment by emasab** [comment]
Hi, you can do it. Try moving your window to approximately the 75% of the top edge of the screen.

**Comment by detly** [comment]
This definitely doesn't work for me. What debugging information can I provide?

**Comment by detly** [comment]
Never mind, I had missed the "without ctrl" part. Works well, thanks!

**Comment by detly** [comment]
The other thing to note is that it doesn't work if you drag to the top middle; it has to be the top and off to the side.

**Comment by emasab** [comment]
Yes, for the top edge, differently from the others, there are 5 zone, the central zone resizes to fullscreen, then there are two lateral zones that resize to the top half, then the corners that resize to the top-left or the top-right quarter.
