### ISSUE TITLE
Tiling improvement

### ISSUE THREAD

**Issue by usbkey9** [emasab/shelltile#71]
Hi,

Is it possible to imitate the default behavior of shell for tiling.
Because I can't use "smart half tiling" feature with your extension

Best

**Comment by usbkey9** [comment]
If is it possible to, the best will be to to the same with corner tiling.
E.g horizontal half tiling with two cornered window

NB: "smart half tiling" feature demo : https://www.youtube.com/watch?v=vfj5KjAm-LE

**Comment by usbkey9** [comment]
More improvement:

It's a detail but is it possible to tiling the last pixel when possible ?
E.g on a 1080p screen, when I tiled a window to the right or to bottom, it missed on pixel

Best

**Comment by emasab** [comment]
The grouping edge tiling feature is included in the latest version
