### ISSUE TITLE
Survey about the new quick tiling feature with screen borders

### ISSUE THREAD

**Issue by emasab** [emasab/shelltile#78]
Here you can send your comments about the new quick tiling feature. 

Is it stable? Does it make ShellTile more usable?

Now it's easier to remove a window from the group, you just move it. Instead if you hold Ctrl while moving or maximizing you keep it in the group. The reason is that if you tile without Ctrl it should not be harder to untile it. What do you think about it?

[Video on YouTube](https://www.youtube.com/watch?v=hNncF9Pc6PY)

**Comment by grossherr** [comment]
It is so far stable for me.

The options of having quarter tiling and vertical half screen tiling are great. Pretty much something gnome should have by default.

But tiling a quarter and then another one, like shown in the video, doesn't group the windows for me. It seems to me like grouping while tiling via edge doesn't work at all.

I'm using:
Ubuntu 18.04.2
GNOME Shell 3.28.3

Running `cat /var/log/syslog | grep -i shelltile` gave me:

> gnome-shell[2517]: JS WARNING: [/home/ng/.local/share/gnome-shell/extensions/ShellTile@emasab.it/tiling.js 1159]: reference to undefined property "group"
> gnome-shell[2517]: JS WARNING: [/home/ng/.local/share/gnome-shell/extensions/ShellTile@emasab.it/tiling.js 528]: reference to undefined property "group"
> gnome-shell-ext[9718]: JS WARNING: [/home/ng/.local/share/gnome-shell/extensions/ShellTile@emasab.it/prefs.js 61]: assignment to undeclared variable setting
> gnome-shell-ext[9718]: JS WARNING: [/home/ng/.local/share/gnome-shell/extensions/ShellTile@emasab.it/prefs.js 107]: assignment to undeclared variable store
> gnome-shell-ext[9718]: JS WARNING: [/home/ng/.local/share/gnome-shell/extensions/ShellTile@emasab.it/prefs.js 113]: assignment to undeclared variable combo
> gnome-shell-ext[9718]: JS WARNING: [/home/ng/.local/share/gnome-shell/extensions/ShellTile@emasab.it/prefs.js 116]: assignment to undeclared variable renderer

In case it matters.

Thanks for the great extension, keep up the work!

**Comment by emasab** [comment]
Hi, thanks for the feedback! be aware that the quick tiling with screen borders works only if the last selected/raised window is the one that you want to join with, not only if it's visible. 
Also, what kind of window have you used? There are some programs like gnome terminal that automatically resize themselves thus breaking the tiling.
