### ISSUE TITLE
version on extensions.gnome.org is greater than master

### ISSUE THREAD

**Issue by skewty** [emasab/shelltile#85]
https://github.com/emasab/shelltile/blob/2205f57664ac69ee405f9fbd5c704a6013d0eedc/metadata.json#L20

What I got from "extensions.gnome.org" shows version 59.

Was the published version for another branch?  Which one?
Where is the newest code?

**Comment by emasab** [comment]
The version is handled by the gnome shell extensions website, I've committed a previous version generated there. The code is the same.
