### ISSUE TITLE
High CPU usage during and after actions on windows

### ISSUE THREAD

**Issue by gedgon** [emasab/shelltile#9]
Hi,
When Shelltile is enabled, gnome-shell process uses a 100% of one CPU core during actions, and, what's more important, significantly more than w/o Shelltile, after action.

Screencast (9MB):
https://www.dropbox.com/s/7vyoii0kb934v53/Shelltile.mp4?dl=0

Systems specs.:
i5 2500
HD 3000 tested /w xf86-video-dirver and Xorg modestetting driver
Arch Linux
kernel 4.7
GNOME 3.20

**Comment by emasab** [comment]
can you try with the same playing video, but after uninstalling Shelltile ?

**Comment by gedgon** [comment]
Works exactly like when Shelltile is disabled (first part of the video, 0-21 sec.)

**Comment by omeryagmurlu** [comment]
I don't have any problems and my specs are kinda similar to yours, HD 4000 with modesetting, Arch, Gnome 3.20. Are you sure it is not caused by any other extension?

**Comment by gedgon** [comment]
I just tried on a fresh user profile. Same issue.

**Comment by alex285** [comment]
I can also reproduce increase on CPU when using Shelltile, but I only noticed after reading this bug and test it. It wasn't noticeable in use. 

nVIDIA / i5
Fedora Rawhide / GNOME 3.22
Kernel 4.5

**Comment by emasab** [comment]
It's strange because there is already a limit of one control every 200 ms. Does it happen moving gnome-terminal too ?

**Comment by gedgon** [comment]
Yes, happens with any window, when moving or tiling. Fortunately, in most cases CPU usage return to normal state.

Screencast with an strange exception (11,5MB):
https://www.dropbox.com/s/w22usc468b5riew/Shelltile2.mp4?dl=0

**Comment by emasab** [comment]
can you try replacing the file

https://github.com/emasab/shelltile/issues/9
[tiling.js.zip](https://github.com/emasab/shelltile/files/457075/tiling.js.zip)

**Comment by gedgon** [comment]
Nothing changed :(

**Comment by emasab** [comment]
and with this one ?
[tiling.js.zip](https://github.com/emasab/shelltile/files/458814/tiling.js.zip)

**Comment by gedgon** [comment]
Still the same.

**Comment by emasab** [comment]
Did you logout from the session and login again after replacing the file (or restarted gnome shell in another way) ? Sorry but I can't reproduce this one

**Comment by gedgon** [comment]
Yes, of course. I did both every time, just to be sure.
That's strange. What version of GNOME are you using?

**Comment by emasab** [comment]
3.18.5

**Comment by emasab** [comment]
another try
[tiling.js.zip](https://github.com/emasab/shelltile/files/458938/tiling.js.zip)

**Comment by gedgon** [comment]
Still nothing with the last one.
I just tired Gnome 3.18.1 (Fedora 23), and it's partially reproducible there. CPU usage when moving windows is higher than w/o Shelltile, but under 50%.
Can you move a window to the left or right screen edge without releasing mouse button and then check the CPU usage? Like this:
![shelltile](https://cloud.githubusercontent.com/assets/7478265/18312050/f3705f3c-7507-11e6-9d33-bf4e0d17364c.gif)

**Comment by gedgon** [comment]
Works like a charm. Thank you very much for this awesome extension and for the fix.
Regards.
