### ISSUE TITLE
Old version on extensions.gnome.org

### ISSUE THREAD

**Issue by Mershl** [emasab/shelltile#91]
The newest version of shelltile on extensions.gnome.org is available for Gnome 3.22 and lower. Due to the many changesets refering to support for 3.30/.32/.34 I assume that the repository has a much newer version of shelltile.

Is the version on git deliberately held back or is a new version stuck in the review process of extensions.gnome.org?

**Comment by emasab** [comment]
Hi the working version list was not updated, the latest version v60 is in process of review on extensions.gnome.org

**Comment by AlexWayfer** [comment]
Here is the progress: https://extensions.gnome.org/review/13519

**Comment by Mershl** [comment]
Thank you both for the clarification. As the review on extensions.gnome.org is already created I'l close this issue as solved.
