### ISSUE TITLE
Shelltile supersedes keyboard commands for tiling

### ISSUE THREAD

**Issue by TheRoarkster** [emasab/shelltile#92]
Just started using this extension, but it seems to **supersede** the keyboard shortcuts that I have set in GNOME Settings for Left Edge Tile, Right Edge Tile, and Maximize (I use `CTL+Left, Right, and Up`, respectively).  When I say supersede, I mean that in GNOME settings the "View on split right" settings gets changed by ShellTile to `Super+Right`, even though I had it set to `Ctl+Right`.  This occurs when I have "Enable Keybindings" turned off.  

When I turn ShellTile's "Enable Keybindings" on **and** set the keybindings in the extension (rather the GNOME Settings) the left and right edge tiling work (though both are more sluggish than the system method), but ShellTile continues to supersede the Maximize setting in GNOME Settings.

**Comment by emasab** [comment]
Hi, ShellTile doesn't supersede the GNOME keybindings, it just adds some new keybindings: 
`<Ctrl><Super>(Left, Right, Up, Down)`. Now, on GNOME the default keybindings default to `<Super>(Left, Right, Up, Down)`. I've tried changing with d-conf the keybindings:

`org.gnome.mutter.keybindings.toggle-tiled-left`, 
`org.gnome.mutter.keybindings.toggle-tiled-right`
`org.gnome.desktop.wm.maximize` 
`org.gnome.desktop.wm.unmaximize` 

to use Ctrl and it works correctly, using `<Ctrl>(Left, Right, Up, Down)` for the GNOME default tiling and maximizing/unmaximizing and `<Ctrl><Super>(Left, Right, Up, Down)` for the ShellTile commands.

**Comment by TheRoarkster** [comment]
Thanks for the response.  I'm going to restart again, but I had to remove ShellTile to keep my preferred `Ctl+Right` for right side tile.  Maybe the issue is something I am missing, but it started when I installed ShellTile.  With "Enable Keybindings" disabled, the problem was still there (i.e., my settings for right side tile of `Ctl+Right` were replaced with `Super+Right` in GNOME Settings).

**Comment by TheRoarkster** [comment]
I just reinstalled the extension and tested again -- same thing.  After about an hour, ShellTile takes over my GNOME keyboard settings and changes my `Ctrl`+(`Left,Right,Up`) to `Super`+(`Left,Right,Up`).  

Attached are images of the settings.  
![Screenshot from 2020-02-04 12-03-42](https://user-images.githubusercontent.com/35146738/73782191-87cf1600-4746-11ea-869e-402014a153ac.png)
![Screenshot from 2020-02-04 12-03-18](https://user-images.githubusercontent.com/35146738/73782192-87cf1600-4746-11ea-9ada-331fa793fd7f.png)

**Comment by emasab** [comment]
I've reproduced it, it happens when you disable the extension, there was some code that reset the keybindings to the default ones, due to a previous (2017) rollback of the keybindings behavior.

I've removed it in the latest commit:
https://github.com/emasab/shelltile/commit/b2a5b32fdfd089167a8ab3bb6c8289e81c3951af
